repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.0  # Use the latest stable version
    hooks:
      - id: clang-format
        args: [--style=file]  # Uses the .clang-format file